config/routes.rb
TrainingAmin::Application.routes.draw do
  resources :categories
  resources :articles
  resources :products
  resources :comments
  resources :users
  resources :countries

  

  
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

 
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  belongs_to :user
  belongs_to :product
  
  has_many :products, :through => :product_category #join table

 has_many :product_categories

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :users


  validates :country, :presence => :true
  validate :valid_code

  def valid_code
  	if self.code => "ID" || self.code => "USA" || self.code => "CHN "
	  return true
	else
	  return false
	end 	
  
  					  
  
end	

app/models/product.rb
class Product < ActiveRecord::Base

#attr_accessible :name, :price, :description

 belongs_to :user
 has_many :categories
 belongs_to :category
 
 has_many :categories, :through => :product_categories
  #join table

 has_many :product_categories

 
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  class Assembly 
  
  
  
    belongs_to :product
    belongs_to :category
    

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :products
  belongs_to :country
  has_many :comments, :dependent => :destroy
  has_many :categories
  


	def valid_first_name

	validates :first_name, :presence => :true, :uniqueness => :true,
				    		:length => { :maximum => 25},
				    		:format => {:with => "/[a-zA-Z\s]+$/"}
	end

	def valid_last_name

	validates :last_name, :presence => :true, :uniqueness => :true,
							:length => { :maximum => 25},
							:format => {:with => "/[a-zA-Z\s]+$/"}

	end

	
	def valid_email
	validates :email, :presence => :true, :uniqueness => :true,
							:format => {:with => "/^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i"}
	end
	
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  layout 'articles'

  def index
    @articles = Article.where("descriptions LIKE '%Lemper%'")
                       .limit(6)
                       .select("title, descriptions")
  end

  
  def new
    @article = Article.new
    
  end
  
  def create
    @article = Article.create(article_params)
    
    if @article.save
      flash[:notice] = "Selamat Sudah Disimpan"
      redirect_to articles_path
      return

    else
      flash[:error] = "Gagal Maning Brooo"
    end

    render :new
    
    
  end 

  def show
    @comments = @article.comments

  end
 
  def edit
      
  end
    
  def destroy
    @article = Article.find_by_id(params[:id])

      if @article.destroy
        flash[:notice] = "Selamat Sudah Didelete"
             
      else
        flash[:error] = "Gagal Delete Brooo"

      end

      redirect_to articles_path


  end
  
  private
  
  def article_params
      params.require(:article).permit(:title, :descriptions, :rating, :user_id)
    end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    session['baru'] = 'Bandung'
  end
  
  def create
    
  end 
    
  def edit
    
  end
    
  def index
   
  end
  
  
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def destroy
	  
	end

	def create
		@comment = Comment.new(comment_params)

	<table border = "2" > 

 	<tr>
 		<TD> Content  </td>
 		<TD> Article ID </TD>
 		<TD> User ID </TD>

 	<tr>
		if @comment.save
			flash (:notice) = "Komentar Masuk"

		else
			flash (:error) = "Komentar Gagal"
	    end

		redirect_to_article_path(@comment.article_id)
	end

	def comment_params
		params.require(:comment) .permit(:content, :article_id)

	end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

    def new
    @countries = Country.new
    end
  
    def create
   
    @country = Country.new(country_params)

    if @country.save
      flash[:notice] = "Selamat Sudah Disimpan"
      redirect_to countries_path
      return

    else
      flash[:error] = "Gagal Brooo"
    end

    render :new
    
    
    end 
    
    def edit
      
    end
    
    def index

      @countries = Country.where("country LIKE '%Serikat%'")
     
    end

    def destroy
      @country = Country.find_by_id(params[:id])

      if @country.destroy
        flash[:notice] = "Selamat Sudah Didelete"
             
      else
        flash[:error] = "Gagal Delete Brooo"

      end

      redirect_to country_path

    end


    private
    
    def country_params
      params.require(:country).permit(:code, :name)
    end

    
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def new
    @product = Product.new 
  end
  
  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = "Selamat Sudah Disimpan"
      redirect_to products_path
      return

    else
      flash[:error] = "Gagal Brooo"
    end

    render :new
    
  end 
    
  def edit
    
  end

  def update
    if @product.save
        flash[:notice] = "Selamat Sudah Diedit"
        redirect_to products_path
        return
    else
      flash[:error] = "Gagal Edit Brooo"
    end
  end

    
    
    def index
      @products = Product.limit(5)
                          .select("name, price, stock, descriptions")
                          .where("name LIKE %Pot%")
    end
      
    def destroy
      @product = Product.find_by_id(params[:id])

      if @product.destroy
        flash[:notice] = "Selamat Sudah Didelete"
             
      else
        flash[:error] = "Gagal Delete Brooo"

      end

      redirect_to products_path
      

    end
    
    def show
       @product = Product.find_by_id(params[:id])
    end

    private

    def find_product
    	@product = Product.find_by_id(1) 
    end

    def product_params
      params.require(:product).permit(:name, :price, :stock, :description)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new
    @user = User.new 
     end
  
    def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notice] = "Selamat Sudah Disimpan"
      redirect_to users_path
      return

    else
      flash[:error] = "Gagal Brooo"
    end

    render :new
    
    end 
    
    def edit
      
    end

    def destroy

      @user = User.find_by_id(params[:id])

      if @user.destroy
        flash[:notice] = "Selamat Sudah Didelete"
             
      else
        flash[:error] = "Gagal Delete Brooo"

      end

      redirect_to users_path

    end
    
    def index
      @users = User.select("first_name, email, age, username")
                  .where("age > ?", 10)
                  .order("first_name ASC")
                  .limit(11)
           
    end

    private

    def user_params
      params.require(:user).permit(:first_name, :email, :username, :password, :dateofbirth, :last_name)
    end
    end

app/helpers/application_helper.rb
module ApplicationHelper


 def list_categories

 	str = "<ul>"

 	Category.all.each do |category|
 		str += "<li>#{category.name}</li>"
 	end

 	return str += "</ul>"
 end

 

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/article/edit.html.erb</p>
<%= @article %>

app/views/articles/index.html.erb
<h1> Selamat Datang <h1>
	<h2>Articles#index</h2>
<p>Find me in app/views/articles/index.html.erb</p>


      <%= flash[:notice] %>


<table border = "1">

 <tr>
 	<TD> Title</TD>
 	<TD> Descriptions </TD>

 </tr>

	<% @articles.each do |article|%>

<tr>
	<TD> <%= link_to article.title, product_path(article.id)%> </TD>
	<TD> <%= article.descriptions %> </TD>
	<td> <%= link_to "delete" , article_path(article.id), :confirm => "Serius neh?", :method => "delete" %> <td> 
	


</tr>
<%end%>


 </table>
      

app/views/articles/new.html.erb
<h1>Articles#now</h1>
<p>Find me in app/views/articles/now.html.erb</p>
<%=session['Baru']%>

<%= form_for @article do |f| %>

 Title: <%= f.text_field :title %>

 Descriptions : <%= f.text_area :descriptions %>

 Rating : <%= f.number_field :rating %>

 User ID : <%= f.text_area :user_id %>

 <%=f.submit :create%>

	<%= link_to "Back to Index", "/articles", :class => "new-article" %>


<%= raw(list_categories) %>



<% end %>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>















































<% @products = product.name%>
<% @products = product.descriptions%>
<% @products = product.price%>
<% @products = product.stock%>
<% link_to = "Back to Index" , :articles %>

app/views/comments/index.html.erb
<table border = "2" > 

 <tr>
 	<TD> Content  </td>
 	<TD> Article ID </TD>
 	<TD> User ID </TD>

 	<tr>

 	

app/views/countries/edit.html.erb
<h1>Countries#edit</h1>
<p>Find me in app/views/countries/edit.html.erb</p>

app/views/countries/index.html.erb
<h1>Countries#index</h1>
<p>Find me in app/views/countries/index.html.erb</p>


      <%= flash[:notice] %>


<table border = "1">

<tr>
 	<TD> Code</TD>
 	<TD> Countries </TD>
 	
</tr>

<% @countries.each do |country|%>

<tr>

	<TD> <%= link_to country.code, country_path(country.id)%> </TD>
	<TD> <%= country.name %> </TD>
	<td> <%= link_to "delete" , country_path(country.id), :confirm => "Serius neh?", :method => "delete" %> </td> 

</tr>

<%end%>


 </table>

app/views/countries/new.html.erb
<h1>Countries#now</h1>
<p>Find me in app/views/countries/new.html.erb</p>
<%=session['Baru']%>

<%= form_for @country do |f| %>

 Code: <%= f.number_field :code %>

 Name : <%= f.text_field :name %>

 

 <%=f.submit :create%>

	<%= link_to "Back to Index", "/countries", :class => "new-article" %>



<%= raw(list_categories) %>



<% end %>

app/views/countries/show.html.erb
<h1>Countries#show</h1>
<p>Find me in app/views/countries/show.html.erb<

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>
<%= @product %>


<%= form_for @product do |f| %>

 Name: <%= f.text_field :name %>

 Price : <%= f.text_field :price %>

 Stock : <%= f.text_field :stock %>

 Description : <%= f.text_area :description %>

 <%=f.submit :create%>

	<%= link_to "Back to Index", "/products", :class => "new-article" %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>



<table border = "1">
 <%= flash[:notice] %>

 <tr>
 	<TD> Name</TD>
 	<TD> Price </TD>
 	<TD> Stock </TD>
 	<TD> Description</TD>
 

 </tr>

<% @products.each do |product|%>

<tr>

	<TD> <%= link_to product.name, product_path(product.id)%> </TD>
	<TD> <%= product.price%> </TD>
	<TD> <%= product.stock%> </TD>
	<TD> <%= product.description%> </TD>
	<td> <%= link_to "edit" , edit_product_path(product.id)%> <td>
	<td> <%= link_to "delete" , product_path(product.id), :confirm => "Serius neh?", :method => "delete" %> <td> 


</tr>
<%end%>


 </table>

app/views/products/new.html.erb
<h1>Products#now</h1>
<p>Find me in app/views/products/now.html.erb</p>
<%=session['Baru']%>

<%= form_for @product do |f| %>

 Name: <%= f.text_field :name %>

 Price : <%= f.text_field :price %>

 Stock : <%= f.text_field :stock %>

 Description : <%= f.text_area :description %>

 <%=f.submit :create%>

	<%= link_to "Back to Index", "/products", :class => "new-article" %>

<%= image_tag '1.jpg', :class => "image", :alt => 'pictures', :width => 200 %>


<%= raw(list_categories) %>



<% end %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

<% @products = product.name%>
<% @products = product.descriptions%>
<% @products = product.price%>
<% @products = product.stock%>
<% link_to = "Back to Index" , :products %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>
<%= @user %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>


      <%= flash[:notice] %>

<table border = "2">

 <tr>
 	<TD> First Name</TD>
 	<TD> Email </TD>
 	<TD> User Name </TD>
 	<TD> Age </TD>
 </tr>

<% @users.each do |user| %>

<tr>

	<TD> <%= user.first_name%> </TD>
	<TD> <%= user.email %> </TD>
	<TD> <%= user.username%> </TD>
	<TD> <%= user.age%> </TD>
	<td> <%= link_to "delete" , user_path(user.id), :confirm => "Serius neh?", :method => "delete" %> <td> 


</tr>
<%end%>


 </table>
      

app/views/users/new.html.erb
<h1>Users#now</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%=session['Baru']%>

<% if @user.errors.any? %>

 <div id="Error Explanation">

 <h2>

 

<%= pluralize(@user.errors.count, "error") %> 

 </h2>

 <ul>

 

<% @user.errors.full_messages.each do |msg| %>

 <li><%= msg %></li>

 <% end %>

 </ul>

 </div>

<% end %>


<%= form_for @user do |f| %>

 Name: <%= f.text_field :first_name %>

 Last Name : <%= f.text_field :last_name %>

 Email : <%= f.text_field :email %>

 Password : <%= f.password_field :password %>
 
 DateBirth : <%= f.date_field :dateofbirth %>

 Age : <%= f.number_field :age %>

 <%=f.submit :create%>

	<%= link_to "Back to Index", "/users", :class => "new-article" %>

<%= image_tag '1.jpg', :class => "image", :alt => 'pictures', :width => 200 %>


<%= raw(list_categories) %>



<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>